#! /bin/bash

# Binder post-build script

# install Poetry
pip install -q 'poetry>=1.1.7,<1.2.0'
# export requirements.txt with Poetry
python -m poetry export -f 'requirements.txt' -o 'requirements.txt'
# uninstall Poetry
pip uninstall -yq 'poetry'
# install packages in requirements.txt
pip install -r ./requirements.txt
# remove requirements.txt
rm ./requirements.txt
