#! /bin/bash

pip install -q 'poetry>=1.1.7,<1.2.0'
python -m poetry export -f 'requirements.txt' -o 'requirements.txt'
pip uninstall -yq 'poetry'
pip install -r ./requirements.txt
rm ./requirements.txt
